version: '3.4'

services:
  sourcingmongodb:
    container_name: sourcingmongodb
    restart: always
    volumes:
       - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
       - "27017:27017"
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "15672:15672" #Yonetim Paneli
        - "5672:5672" #AMQP Protokolu

  sourcingmssqldb:
    container_name: sourcingmssqldb
    ports:
        - "1433:1433"
    environment:
       SA_PASSWORD: "jvCYrGm9xhk9yBCw"
       ACCEPT_EULA: "Y"

  esourcing.products:
    container_name: esourcingproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingmongodb:27017"
    depends_on:
        - sourcingmongodb
    ports:
      - "8000:80"
    volumes:
         - ${HOME}/.aspnet/Https:/root/.aspnet/https:ro
         - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
   
  esourcing.sourcing:
    container_name: esourcingsourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://sourcingmongodb:27017"
      - "EventBusSettings:HostName=rabbitmq"
    depends_on:
        - sourcingmongodb
        - rabbitmq
    volumes:
         - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
         - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8001:80" 